# Ansible Playbook

- name: Deploy Application
  hosts: target_hosts
  become: yes
  tasks:
    - name: Ensure Docker is installed
      become: yes
      apt:
        name: docker.io
        state: present

    - name: Copy Docker Compose file
      copy:
        src: /path/to/docker-compose.yml
        dest: /home/user/docker-compose.yml
      become: yes

    - name: Pull Docker image
      docker_image:
        name: gcr.io/project-id/image-name:tag
        state: present

    - name: Run Docker container
      docker_container:
        name: my-container
        image: gcr.io/project-id/image-name:tag
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        volumes:
          - /path/to/volume:/container/path/to/volume
        env:
          EXAMPLE_ENV_VAR: "example_value"
