name: Build and Push Docker Image to artifact registry - Dev version

on:
  pull_request:
    branches:
      - main:
  push:
    branches:
      - "*"

jobs:
  build_maven:
    runs-on: self-hosted
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests with Maven
        run: mvn test
        
      - name: Static Code Analysis with Checkstyle
        run: mvn checkstyle:checkstyle
      
      - name: Save JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: ${{ github.workspace }}/target/*.jar

  push-to-registry:
    runs-on: self-hosted
    needs: build_maven

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: target/
      
      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          cleanup_credentials: false
      
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Docker auth
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Build Docker Image
        run: docker build -t us-central1-docker.pkg.dev/petclinic-capstone-project/capstone-project-registry/dev-petclinic:latest .
      
      - name: Docker push Image
        run: docker push us-central1-docker.pkg.dev/petclinic-capstone-project/capstone-project-registry/dev-petcliniclatest
